version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(deps)"
    groups:
      rust-minor-patch:
        update-types:
          - "minor"
          - "patch"
      rust-major:
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(actions)"
    groups:
      github-actions-minor-patch:
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        update-types:
          - "major"
