{{- if .Values.catalogPublishJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bijux-atlas.fullname" . }}-catalog-publish
  labels:
    {{- include "bijux-atlas.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.catalogPublishJob.backoffLimit }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bijux-atlas.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: catalog-publish
          image: {{ .Values.catalogPublishJob.image }}
          command:
            {{- toYaml .Values.catalogPublishJob.command | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "bijux-atlas.fullname" . }}-config
          {{- if .Values.store.credentialsSecretName }}
            - secretRef:
                name: {{ .Values.store.credentialsSecretName }}
          {{- end }}
{{- end }}
