{{- if and .Values.store.credentialsSecretName .Values.store.manageCredentialsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.store.credentialsSecretName }}
  labels:
    {{- include "bijux-atlas.labels" . | nindent 4 }}
type: Opaque
stringData:
  ATLAS_STORE_ACCESS_KEY_ID: ""
  ATLAS_STORE_SECRET_ACCESS_KEY: ""
{{- end }}
