[package]
name = "bijux-dev-atlas"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
regex = "1"
bijux-dev-atlas-core.workspace = true
bijux-dev-atlas-model.workspace = true
bijux-dev-atlas-adapters.workspace = true
bijux-dev-atlas-policies.workspace = true

[dev-dependencies]
assert_cmd = "2"

[[bin]]
name = "bijux-dev-atlas"
path = "src/main.rs"
