[package]
name = "bijux-atlas-model"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bijux-atlas-core.workspace = true
serde.workspace = true
serde_json.workspace = true

[lib]
path = "src/lib.rs"
