{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bijux-atlas.fullname" . }}
  labels:
    {{- include "bijux-atlas.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bijux-atlas.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
