replicaCount: 1

image:
  repository: ghcr.io/bijux/bijux-atlas
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

cache:
  warmupEnabled: true
  pinnedDatasets: []

catalog:
  endpoint: ""

store:
  endpoint: "http://minio.atlas-e2e.svc.cluster.local:9000"
  s3PresignedBaseUrl: ""
  credentialsSecretName: ""

server:
  enableDebugDatasets: true
  cachedOnlyMode: false
  readinessRequiresCatalog: false
  startupProbePath: /healthz
  readinessProbePath: /healthz

serviceMonitor:
  enabled: false

alertRules:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false
