services:
  prometheus:
    image: prom/prometheus:v2.54.1@sha256:f6639335d34a77d9d9db382b92eeb7fc00934be8eae81dbc03b31cfe90411a94
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=2h"
    ports:
      - "19090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana:11.2.0@sha256:408afb9726de5122b00a2576763a8a57a3c86d5b0eff5305bc994ceb3eb96c3f
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    ports:
      - "13000:3000"
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0@sha256:a2a52e43c1a80aa94120ad78c2db68780eb90e6d11c8db5b3ce2f6a0cc6b5029
    command:
      - "--config=/etc/otelcol/config.yaml"
    ports:
      - "14317:4317"
      - "14318:4318"
    volumes:
      - ./otel-collector.yaml:/etc/otelcol/config.yaml:ro
