apiVersion: v1
kind: ConfigMap
metadata:
  name: atlas-observability-prometheus-config
  namespace: atlas-observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: atlas
        static_configs:
          - targets: ["bijux-atlas.atlas-e2e.svc.cluster.local:8080"]
